title: Simply Jekyll
description: This is a simple motherfucking jekyll theme
baseurl: ""
url: "github.tk"

email: email@email.com
twitter_username: tweeter
github_username: gethub

markdown: kramdown
includeFooter: false